const translations = {
    uk: {
        title_main: "Головна сторінка",
        title_catalog: "Каталог автомобілів", 
        nav_home: "Головна", 
        nav_catalog: "Каталог", 
        nav_contacts: "Зв'язок з нами",
        catalog_header: "Наш Каталог", 
        car_types_title: "Класи автомобілів",

        advantages_title: "Чому ви повинні обрати нас?",
        adv_1_title: "Найкращі ціни",
        adv_1_text: "Ми пропонуємо конкурентоспроможні ціни на ринку та гнучкі умови оплати для кожного клієнта.",
        adv_2_title: "Перевірені авто",
        adv_2_text: "Кожен автомобіль у нашому каталозі проходить ретельну технічну та юридичну перевірку.",
        adv_3_title: "Широкий асортимент",
        adv_3_text: "Від повсякденних міських седанів до рідкісних ексклюзивних гіперкарів та JDM легенд.",
        adv_4_title: "Підтримка 24/7",
        adv_4_text: "Наша команда професіоналів завжди готова допомогти вам із вибором та оформленням авто.",

        filter_price: "Ціна", 
        filter_brand: "Марка", 
        filter_body: "Кузов",
        filter_country: "Країна", 
        filter_mileage: "Пробіг", 
        filter_class: "Клас авто", 
        filter_sort: "Сортувати за",
        filter_year: "Рік випуску",

        opt_all: "Всі",
        opt_all_prices: "Всі ціни",
        opt_all_brands: "Всі марки",
        opt_all_bodies: "Всі кузови",
        opt_all_countries: "Всі країни",
        opt_all_mileages: "Будь-який пробіг",
        opt_all_classes: "Всі класи",
        opt_new_car: "Без пробігу (Нова)",
        
        price_up_to_30: "до $30,000",
        price_30_100: "$30,000 - $100,000",
        price_over_100: "Понад $100,000",

        body_coupe: "Купе", 
        body_sedan: "Седан", 
        body_suv: "Позашляховик",

        country_germany: "Німеччина", 
        country_italy: "Італія", 
        country_japan: "Японія", 
        country_france: "Франція",

        mileage_up_to_50: "до 50,000 км",
        mileage_over_50: "Понад 50,000 км",

        type_sport: "Спорткари", 
        type_super: "Суперкари", 
        type_hyper: "Гіперкари", 
        type_suv: "Позашляховики (SUV)",

        sort_price_asc: "Ціна: від дешевих", 
        sort_price_desc: "Ціна: від дорогих", 
        sort_year_desc: "Новіші за роком",
        sort_mileage_asc: "Найменший пробіг", 

        no_cars: "Автомобілів не знайдено", 
        text_year: "рік", 
        text_km: "км",
        text_from: "Знайдено авто:", 
        text_out_of: "з",

        footer_about_title: "Про нас",
        footer_about_text: "Ми пропонуємо найкращі автомобілі для ваших незабутніх поїздок. Надійність та якість — наш пріоритет.",
        footer_contacts_title: "Контакти",
        footer_address: "м. Київ, вул. Автомобільна, 1",
        footer_social_title: "Соцмережі",
        footer_rights: "Всі права захищені."
    },
    en: {
        title_main: "Home Page",
        title_catalog: "Car Catalog", 
        nav_home: "Home", 
        nav_catalog: "Catalog", 
        nav_contacts: "Contact us",
        catalog_header: "Our Catalog", 
        car_types_title: "Car Classes",

        advantages_title: "Why Should You Choose Us?",
        adv_1_title: "Best Prices",
        adv_1_text: "We offer highly competitive market prices and flexible payment options for every client.",
        adv_2_title: "Verified Cars",
        adv_2_text: "Every vehicle in our catalog undergoes strict technical and background checks.",
        adv_3_title: "Wide Range",
        adv_3_text: "From everyday city sedans to rare exclusive hypercars and legendary JDM models.",
        adv_4_title: "24/7 Support",
        adv_4_text: "Our team of professionals is always available to help you choose and acquire your car.",

        filter_price: "Price", 
        filter_brand: "Brand", 
        filter_body: "Body Type",
        filter_country: "Country", 
        filter_mileage: "Mileage", 
        filter_class: "Car Class", 
        filter_sort: "Sort by",
        filter_year: "Year of release",

        opt_all: "All",
        opt_all_prices: "All prices",
        opt_all_brands: "All brands",
        opt_all_bodies: "All body types",
        opt_all_countries: "All countries",
        opt_all_mileages: "Any mileage",
        opt_all_classes: "All classes",
        opt_new_car: "No mileage (New)",

        price_up_to_30: "up to $30,000",
        price_30_100: "$30,000 - $100,000",
        price_over_100: "Over $100,000",

        body_coupe: "Coupe", 
        body_sedan: "Sedan", 
        body_suv: "SUV",

        country_germany: "Germany", 
        country_italy: "Italy", 
        country_japan: "Japan",
        country_france: "France",

        mileage_up_to_50: "up to 50,000 km",
        mileage_over_50: "Over 50,000 km",

        type_sport: "Sports Cars", 
        type_super: "Supercars", 
        type_hyper: "Hypercars", 
        type_suv: "SUVs",

        sort_price_asc: "Price: low to high", 
        sort_price_desc: "Price: high to low", 
        sort_year_desc: "Newer by year",
        sort_mileage_asc: "Lowest mileage", 

        no_cars: "No cars found", 
        text_year: "y.o.", 
        text_km: "km",
        text_from: "Found cars:", 
        text_out_of: "of",

        footer_about_title: "About Us",
        footer_about_text: "We offer the best cars for your unforgettable trips. Reliability and quality are our priority.",
        footer_contacts_title: "Contacts",
        footer_address: "Kyiv, Avtomobilna str., 1",
        footer_social_title: "Social Media",
        footer_rights: "All rights reserved."
    },
    ru: {
        title_main: "Главная страница",
        title_catalog: "Каталог автомобилей", 
        nav_home: "Главная", 
        nav_catalog: "Каталог", 
        nav_contacts: "Связь с нами",
        catalog_header: "Наш Catalog", 
        car_types_title: "Классы автомобилей",

        advantages_title: "Почему вы должны выбрать нас?",
        adv_1_title: "Лучшие цены",
        adv_1_text: "Мы предлагаем конкурентоспособные цены на рынке и гибкие условия оплаты для каждого клиента.",
        adv_2_title: "Проверенные авто",
        adv_2_text: "Каждый автомобиль в нашем каталоге проходит тщательную техническую и юридическую проверку.",
        adv_3_title: "Широкий ассортимент",
        adv_3_text: "От повседневных городских седанов до редких эксклюзивных гиперкаров и JDM легенд.",
        adv_4_title: "Поддержка 24/7",
        adv_4_text: "Наша команда профессионалов всегда готова помочь вам с выбором и оформлением авто.",

        filter_price: "Цена", 
        filter_brand: "Марка", 
        filter_body: "Кузов",
        filter_country: "Страна", 
        filter_mileage: "Пробег", 
        filter_class: "Класс авто", 
        filter_sort: "Сортировка",
        filter_year: "Год выпуска",

        opt_all: "Все",
        opt_all_prices: "Все цены",
        opt_all_brands: "Все марки",
        opt_all_bodies: "Все кузова",
        opt_all_countries: "Все страны",
        opt_all_mileages: "Любой пробег",
        opt_all_classes: "Все классы",
        opt_new_car: "Без пробега (Новая)",

        price_up_to_30: "до $30,000",
        price_30_100: "$30,000 - $100,000",
        price_over_100: "Более $100,000",

        body_coupe: "Купе", 
        body_sedan: "Седан", 
        body_suv: "Внедорожник",

        country_germany: "Германия", 
        country_italy: "Италия", 
        country_japan: "Япония",
        country_france: "Франция",

        mileage_up_to_50: "до 50,000 км",
        mileage_over_50: "Свыше 50,000 км",

        type_sport: "Спорткары", 
        type_super: "Суперкари", 
        type_hyper: "Гиперкары", 
        type_suv: "Внедорожники (SUV)",

        sort_price_asc: "Цена: от дешевых", 
        sort_price_desc: "Цена: от дорогих", 
        sort_year_desc: "Более новые по году",
        sort_mileage_asc: "Наименьший пробег", 

        no_cars: "Автомобилей не найдено", 
        text_year: "г.", 
        text_km: "км",
        text_from: "Найдено авто:", 
        text_out_of: "из",

        footer_about_title: "О нас",
        footer_about_text: "Мы предлагаем лучшие автомобили для ваших незабываемых поездок. Надежность и качество — наш приоритет.",
        footer_contacts_title: "Контакты",
        footer_address: "г. Киев, ул. Автомобильная, 1",
        footer_social_title: "Соцсети",
        footer_rights: "Все права защищены."
    }
};

const CarsCatalogData = [
    { id: 'car1', brand: 'Porsche', model: '911 Carrera Cabriolet', class: 'sport', body: 'Coupe', country: 'Німеччина', year: 2022, mileage: 15000, price: 120000, img: 'pics/car1.jpg' },
    { id: 'car3', brand: 'Ferrari', model: 'F8 Tributo', class: 'super', body: 'Coupe', country: 'Італія', year: 2021, mileage: 4000, price: 280000, img: 'pics/car2.jpg' },
    { id: 'car5', brand: 'Lamborghini', model: 'Revuelto', class: 'hyper', body: 'Coupe', country: 'Італія', year: 2025, mileage: 500, price: 729000, img: 'pics/car3.jpg' },
    { id: 'car8', brand: 'Nissan', model: 'Skyline GT-R R32', class: 'sport', body: 'Coupe', country: 'Японія', year: 1994, mileage: 112000, price: 45000, img: 'pics/car4.jpg' },
    { id: 'car9', brand: 'Mitsubishi', model: 'Lancer Evolution X', class: 'sport', body: 'Sedan', country: 'Японія', year: 2015, mileage: 65000, price: 28000, img: 'pics/car5.jpg' },
    { id: 'car10', brand: 'Bugatti', model: 'Chiron Grand Sport', class: 'hyper', body: 'Coupe', country: 'Франція', year: 2021, mileage: 1200, price: 3200000, img: 'pics/car6.jpg' },
    { id: 'car11', brand: 'Porsche', model: 'Cayenne Turbo GT', class: 'suv', body: 'SUV', country: 'Німеччина', year: 2024, mileage: 0, price: 210000, img: 'pics/car7.jpg' }
];